/// Type-safe NEAR Protocol JSON-RPC client, generated from the official
/// nearcore OpenAPI specification.
///
/// Pure Dart — runs identically on native (AOT: mobile, desktop, server) and
/// web (compiled to JavaScript / WASM). The client and all request/response
/// models are generated by `tool/generate.dart` and kept in sync with
/// nearcore by a scheduled CI workflow.
///
/// ```dart
/// final rpc = NearJsonRpcClient(endpoint: 'https://test.rpc.fastnear.com');
/// final status = await rpc.status();
/// print(status); // typed RpcStatusResponse
/// ```
library near_jsonrpc_client;

export 'src/client.g.dart';
export 'src/models.g.dart';
