import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';
import 'package:near_dart/near_dart.dart';

/// Response from transaction status queries.
///
/// Contains the final execution outcome of a transaction and all receipts.
@immutable
class TransactionResponse extends Equatable {
  const TransactionResponse({
    required this.status,
    required this.transaction,
    required this.transactionOutcome,
    required this.receiptsOutcome,
  });

  factory TransactionResponse.fromJson(Map<String, dynamic> json) {
    return TransactionResponse(
      status: TransactionStatus.fromJson(json['status']),
      transaction: TransactionView.fromJson(
        json['transaction'] as Map<String, dynamic>,
      ),
      transactionOutcome: ExecutionOutcomeWithId.fromJson(
        json['transaction_outcome'] as Map<String, dynamic>,
      ),
      receiptsOutcome: (json['receipts_outcome'] as List<dynamic>)
          .map(
            (e) => ExecutionOutcomeWithId.fromJson(e as Map<String, dynamic>),
          )
          .toList(),
    );
  }

  /// The final status of the transaction.
  final TransactionStatus status;

  /// The original transaction.
  final TransactionView transaction;

  /// The outcome of the transaction execution.
  final ExecutionOutcomeWithId transactionOutcome;

  /// The outcomes of all receipts generated by the transaction.
  final List<ExecutionOutcomeWithId> receiptsOutcome;

  @override
  List<Object?> get props => [
    status,
    transaction,
    transactionOutcome,
    receiptsOutcome,
  ];
}

/// The status of a transaction.
@immutable
sealed class TransactionStatus extends Equatable {
  const TransactionStatus();

  factory TransactionStatus.fromJson(dynamic json) {
    if (json is String) {
      if (json == 'Unknown') return const TransactionStatusUnknown();
    }
    if (json is Map<String, dynamic>) {
      if (json.containsKey('SuccessValue')) {
        return TransactionStatusSuccess(value: json['SuccessValue'] as String?);
      }
      if (json.containsKey('SuccessReceiptId')) {
        return TransactionStatusSuccessReceipt(
          receiptId: json['SuccessReceiptId'] as String,
        );
      }
      if (json.containsKey('Failure')) {
        return TransactionStatusFailure(
          error: json['Failure'] as Map<String, dynamic>,
        );
      }
    }
    return const TransactionStatusUnknown();
  }
}

/// Transaction status is unknown.
@immutable
class TransactionStatusUnknown extends TransactionStatus {
  const TransactionStatusUnknown();

  @override
  List<Object?> get props => [];
}

/// Transaction succeeded with a return value.
@immutable
class TransactionStatusSuccess extends TransactionStatus {
  const TransactionStatusSuccess({this.value});

  /// Base64-encoded return value, or null if empty.
  final String? value;

  @override
  List<Object?> get props => [value];
}

/// Transaction succeeded and created a receipt.
@immutable
class TransactionStatusSuccessReceipt extends TransactionStatus {
  const TransactionStatusSuccessReceipt({required this.receiptId});

  /// The receipt ID that was created.
  final String receiptId;

  @override
  List<Object?> get props => [receiptId];
}

/// Transaction failed with an error.
@immutable
class TransactionStatusFailure extends TransactionStatus {
  const TransactionStatusFailure({required this.error});

  /// The error details.
  final Map<String, dynamic> error;

  @override
  List<Object?> get props => [error];
}

/// A view of the transaction.
@immutable
class TransactionView extends Equatable {
  const TransactionView({
    required this.signerId,
    required this.publicKey,
    required this.nonce,
    required this.receiverId,
    required this.hash,
    required this.actions,
  });

  factory TransactionView.fromJson(Map<String, dynamic> json) {
    return TransactionView(
      signerId: json['signer_id'] as String,
      publicKey: json['public_key'] as String,
      nonce: json['nonce'] as int,
      receiverId: json['receiver_id'] as String,
      hash: json['hash'] as String,
      actions: (json['actions'] as List<dynamic>).toList(),
    );
  }

  /// The account that signed the transaction.
  final String signerId;

  /// The public key used to sign.
  final String publicKey;

  /// The nonce for this transaction.
  final int nonce;

  /// The receiver account.
  final String receiverId;

  /// The transaction hash.
  final String hash;

  /// The actions in this transaction.
  final List<dynamic> actions;

  @override
  List<Object?> get props => [
    signerId,
    publicKey,
    nonce,
    receiverId,
    hash,
    actions,
  ];
}

/// Execution outcome with its ID.
@immutable
class ExecutionOutcomeWithId extends Equatable {
  const ExecutionOutcomeWithId({
    required this.id,
    required this.outcome,
    this.blockHash,
  });

  factory ExecutionOutcomeWithId.fromJson(Map<String, dynamic> json) {
    return ExecutionOutcomeWithId(
      id: json['id'] as String,
      outcome: ExecutionOutcome.fromJson(
        json['outcome'] as Map<String, dynamic>,
      ),
      blockHash: json['block_hash'] as String?,
    );
  }

  /// The ID (hash) of this execution.
  final String id;

  /// The execution outcome.
  final ExecutionOutcome outcome;

  /// The block hash where this was executed.
  final String? blockHash;

  @override
  List<Object?> get props => [id, outcome, blockHash];
}

/// The outcome of an execution.
@immutable
class ExecutionOutcome extends Equatable {
  const ExecutionOutcome({
    required this.logs,
    required this.receiptIds,
    required this.gasBurnt,
    required this.tokensBurnt,
    required this.executorId,
    required this.status,
  });

  factory ExecutionOutcome.fromJson(Map<String, dynamic> json) {
    return ExecutionOutcome(
      logs: (json['logs'] as List<dynamic>).map((e) => e as String).toList(),
      receiptIds: (json['receipt_ids'] as List<dynamic>)
          .map((e) => e as String)
          .toList(),
      gasBurnt: json['gas_burnt'] as int,
      tokensBurnt: NearToken.fromYocto(json['tokens_burnt'] as String),
      executorId: json['executor_id'] as String,
      status: TransactionStatus.fromJson(json['status']),
    );
  }

  /// Logs produced during execution.
  final List<String> logs;

  /// Receipt IDs generated during execution.
  final List<String> receiptIds;

  /// Gas burnt during execution.
  final int gasBurnt;

  /// Tokens burnt during execution.
  final NearToken tokensBurnt;

  /// The account that executed this.
  final String executorId;

  /// The execution status.
  final TransactionStatus status;

  @override
  List<Object?> get props => [
    logs,
    receiptIds,
    gasBurnt,
    tokensBurnt,
    executorId,
    status,
  ];
}
