name: near_wallet_connect_example
description: Minimal drop-in example for near_wallet_connect.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  near_wallet_connect:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
